### ISSUE TITLE
Decide on hosting platform

### ISSUE THREAD

**Issue by w-shackleton** [WildPetScience/Condor#1]
I suggest Google App Engine, using NDB for storage. Discuss.

**Comment by rogersnm** [comment]
Google App Engine looks like a good choice; is an NDB API available for Java? (https://cloud.google.com/appengine/docs/java/storage)

**Comment by w-shackleton** [comment]
If NDB isn't available then DB is fine.

**Comment by w-shackleton** [comment]
Heroku or GAE?

**Comment by Baltoli** [comment]
I have a bit of experience with Heroku, and if we go with Grails it's supported officially (though in beta), while SparkJava looks quite fiddly. 

GAE seems more opinionated on project layout etc, while Heroku will run most anything you throw at it.

As for deployment, you add Heroku as another remote git repository, then run `$ git push heroku master` to deploy. I think it would be possible to set that up as a commit hook or something so that we can get automatic deployment from master.

**Comment by w-shackleton** [comment]
That seems like a nice way of doing things.

I'm settled on Heroku. Anyone else want to say otherwise?
